apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace : chat-app-ns
type: Opaque
data:
  jwt: YjU0MjBlZjg3ZDQ5ZDliNDZmZjVmN2RiYzY4MDBmNzdmNDZiYmEwNjg0ZDY5ZTRiYTRmODZmZTc2Yjg4M2M1NTlhNmZiZjE5
